## Specify the stages of the pipeline
stages:
  - stage: Build_Docker_Image
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
            displayName: 'Checkout repo'
         
          - script: |
              echo "Building Docker image..."
              docker build -t awesome-fastapi:$(Build.SourceVersion).
            displayName: 'Build Docker Image'
            