
stages:
  - stage: Push_Image
    jobs:
      - job: push_image
        displayName: 'Build and Push Docker Image'
        pool:
          vmImage: 'ubuntu-latest'

          steps:
            - checkout: self
              displayName: 'Checkout repo'

### Push the Docker image to Azure Container Registry ### 
            - task: Docker@2
              displayName: 'Build and Push Docker Image to ACR'
              inputs:
                command: buildAndPush
                repository: $(imageRepository)                # e.g. myacr.azurecr.io/myapp
                dockerfile: $(src/Dockerfile)                # e.g. src/Dockerfile
                containerRegistry: $(dockerRegistryServiceConnection)  # name of your ADO service connection to ACR  
                tags: |
                  latest
                  $(Build.BuildId)
                
