on:
    push:
      branches:
        - main
    workflow_dispatch:

jobs:
    terraform-lint:
        uses: ./.github/workflows/terraform-lint.yml
        permissions:
            contents: read
        secrets: inherit
    terraform-apply:
        uses: ./.github/workflows/terraform-apply.yml
        needs: terraform-lint
        permissions:
            contents: read
        secrets: inherit