on:
    push:
      branches:
        - main
    workflow_dispatch:

jobs:
    terraform-apply-pipelines:
        uses: ./.github/workflows/terraform-apply-pipelines.yml
        permissions:
            contents: read
        secrets: inherit